[package]
name = "bluetooth_wrapper"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
btleplug = {version = "0.11.5", features = ["serde_cr"]}
futures = "0.3.30"
tokio = {version = "1.36.0", features = ["full"]}
uuid = "1.8.0"

